competitions = {
        "titanic-gettingStarted" : "Titanic: Machine Learning from Disaster",
        "digit-recognizer" : "Digit Recognizer",
        "RxVolumePrediction" : "Prescription Volume Prediction",
        "DarkWorlds" : "Observing Dark Worlds",
        "customer-retention" : "Will I Stay or Will I Go?",
        "us-census-challenge" : "U.S. Census Return Rate Challenge (Visualization Competition)",
        "predict-closed-questions-on-stack-overflow" : "Predict Closed Questions on Stack Overflow",
        "global-energy-forecasting-competition-2012-load-forecasting" : "Global Energy Forecasting Competition 2012 - Load Forecasting",
        "GEF2012-wind-forecasting" : "Global Energy Forecasting Competition 2012 - Wind Forecasting",
        "MerckActivity" : "Merck Molecular Activity Challenge",
        "cir-prospect" : "Follow the Money: Investigative Reporting Prospect",
        "job-recommendation" : "Job Recommendation Challenge",
        "acm-sf-chapter-hackathon-big" : "Data Mining Hackathon on BIG DATA (7GB) Best Buy mobile web site",
        "acm-sf-chapter-hackathon-small" : "Data Mining Hackathon on (20 mb) Best Buy mobile web site - ACM SF Bay Area Chapter",
        "cprod1" : "CPROD1: Consumer PRODucts contest #1",
        "detecting-insults-in-social-commentary" : "Detecting Insults in Social Commentary",
        "Raising-Money-to-Fund-an-Organizational-Mission" : "Raising Money to Fund an Organizational Mission",
        "GestureChallenge2" : "CHALEARN Gesture Challenge 2",
        "pf2012-diabetes" : "Practice Fusion Diabetes Classification",
        "pf2012-at" : "Practice Fusion Analyze This! 2012 - Open Challenge",
        "predict-wordpress-likes" : "GigaOM WordPress Challenge: Splunk Innovation Prospect",
        "asap-sas" : "The Hewlett Foundation: Short Answer Scoring",
        "emc-data-science" : "EMC Israel Data Science Challenge",
        "harvard-business-review-vision-statement-prospect" : "Harvard Business Review 'Vision Statement' Prospect",
        "msdchallenge" : "Million Song Dataset Challenge",
        "MusicHackathon" : "EMI Music Data Science Hackathon - July 21st - 24 hours",
        "FacebookRecruiting" : "Facebook Recruiting Competition",
        "online-sales" : "Online Product Sales",
        "pf2012" : "Practice Fusion Analyze This! 2012 - Prediction Challenge",
        "twitter-personality-prediction" : "Personality Prediction Based on Twitter Stream",
        "twitter-psychopathy-prediction" : "Psychopathy Prediction Based on Twitter Usage",
        "bioresponse" : "Predicting a Biological Response",
        "asap-aes" : "The Hewlett Foundation: Automated Essay Scoring",
        "benchmark-bond-trade-price-challenge" : "Benchmark Bond Trade Price Challenge",
        "dsg-hackathon" : "EMC Data Science Global Hackathon (Air Quality Prediction)",
        "awic2012" : "ICFHR 2012 - Arabic Writer Identification",
        "emvic" : "Eye Movements Verification and Identification Competition",
        "GestureChallenge" : "CHALEARN Gesture Challenge",
        "WhatDoYouKnow" : "What Do You Know?",
        "AlgorithmicTradingChallenge" : "Algorithmic Trading Challenge",
        "DontGetKicked" : "Don't Get Kicked!",
        "GiveMeSomeCredit" : "Give Me Some Credit",
        "PhotoQualityPrediction" : "Photo Quality Prediction",
        "SemiSupervisedFeatureLearning" : "Semi-Supervised Feature Learning",
        "ClaimPredictionChallenge" : "Claim Prediction Challenge (Allstate)",
        "dunnhumbychallenge" : "dunnhumby's Shopper Challenge",
        "wikichallenge" : "Wikipedia's Participation Challenge",
        "mdm" : "Mapping Dark Matter",
        "overfitting" : "Don't Overfit!",
        "ChessRatings2" : "Deloitte/FIDE Chess Rating Challenge",
        "WIC2011" : "ICDAR 2011 - Arabic Writer Identification",
        "stayalert" : "Stay Alert! The Ford Challenge",
        "unimelb" : "Predict Grant Applications",
        "RTA" : "RTA Freeway Travel Time Prediction",
        "R" : "R Package Recommendation Engine",
        "socialNetwork" : "IJCNN Social Network Challenge ",
        "tourism2" : "Tourism Forecasting Part Two",
        "chess" : "Chess ratings - Elo versus the Rest of the World",
        "informs2010" : "INFORMS Data Mining Contest 2010",
        "tourism1" : "Tourism Forecasting Part One",
        "hivprogression" : "Predict HIV Progression",
        "worldcup2010" : "World Cup 2010 - Take on the Quants",
        "worldcupconf" : "World Cup 2010 - Confidence Challenge",
        "Eurovision2010" : "Forecast Eurovision Voting",
        "columbia-university-introduction-to-data-science-fall-2012" : "Columbia University - Introduction to Data Science, Fall 2012",
}